services:
  - type: web
    name: argo-float-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python Prototype/openRouter_using_langchain.py
    envVars:
      - key: OPENROUTER_API_KEY
        sync: false
